#!/usr/bin/env python
"""
Reads ~/.config/dconf.user.d/* as JSON files
and ensures dconf has these values set.
"""
from __future__ import print_function
import os, sys
from gi.repository import Gio
import json
def p(*a):
	print(*a, file=sys.stderr)
base = os.path.expanduser("~/.config/dconf.user.d")
if os.path.exists(base):
	for filename in sorted(os.listdir(base)):
		p("Processing: %s" % (filename,))
		with open(os.path.join(base, filename)) as f:
			overrides = json.load(f)
		for (key, val) in overrides.items():
			subject, var = key.rsplit(".", 1)
			settings = Gio.Settings.new(subject)
			current = settings[var]
			# p("%s=%r" % (key, current))
			if current != val:
				p("SET: %s=%r" % (key, val))
				settings[var] = val
			else:
				p("  (already set: %s)" % (key,))
else:
	p("No user overrides found (%s)" % (base,))
	sys.exit(1)
